// appActions
export const OPEN_NEW_POST_MENU = 'OPEN_NEW_POST_MENU';
export const CLOSE_NEW_POST_MENU = 'CLOSE_NEW_POST_MENU';
export const ACTIVATE_EDIT_MODE_OF_POST = 'ACTIVATE_EDIT_MODE_OF_POST';
export const DEACTIVATE_EDIT_MODE_OF_POST = 'DEACTIVATE_EDIT_MODE_OF_POST';
export const OPEN_NEW_COMMENT_MENU = 'OPEN_NEW_COMMENT_MENU';
export const CLOSE_NEW_COMMENT_MENU = 'CLOSE_NEW_COMMENT_MENU';
export const ACTIVATE_EDIT_MODE_OF_COMMENT = 'ACTIVATE_EDIT_MODE_OF_COMMENT';
export const DEACTIVATE_EDIT_MODE_OF_COMMENT = 'DEACTIVATE_EDIT_MODE_OF_COMMENT';
export const FINISH_INITIAL_LOADING = 'FINISH_INITIAL_LOADING';

// categoryActions
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';

// commentActions
export const FETCH_COMMENTS_OF_POST = 'FETCH_COMMENTS_OF_POST';
export const ADD_NEW_COMMENT_TO_POST = 'ADD_NEW_COMMENT_TO_POST';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const UP_VOTE_COMMENT = 'UP_VOTE_COMMENT';
export const DOWN_VOTE_COMMENT = 'DOWN_VOTE_COMMENT';

// postActions
export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_OF_SELECTED_CATEGORY = 'FETCH_POSTS_OF_SELECTED_CATEGORY';
export const FETCH_POST = 'FETCH_POST';
export const CREATE_POST = 'CREATE_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const DELETE_POST = 'DELETE_POST';
export const UP_VOTE_POST = 'UP_VOTE_POST';
export const DOWN_VOTE_POST = 'DOWN_VOTE_POST';
